# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[(b'CAD', 'Canadian Dollar'), (b'USD', 'United States Dollar')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'orders_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'PS', 'Processing'), (b'BCO', 'Being Checked Out'), (b'IP', 'Incomplete'), (b'CP', 'Complete')], max_length=4)),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(related_name='stores', to='order_app.InventoryItem')),
            ],
            options={
                'db_table': 'orders_store',
            },
        ),
    ]
