# Generated by Django 3.0.2 on 2020-01-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20200128_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PS', 'Processing'), ('BCO', 'Being Checked Out'), ('IP', 'Incomplete'), ('CP', 'Complete')], max_length=20),
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='order_app.Order')),
            ],
            options={
                'db_table': 'orders_purchased',
            },
        ),
    ]
